config/routes.rb
Rails.application.routes.draw do
  resources :bridges
  devise_for :users
  root "bridges#index"

end

app/models/bridge.rb
class Bridge < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bridges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bridges_controller.rb
class BridgesController < ApplicationController
  before_action :set_bridge, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @bridges = Bridge.all
  end

  def show
  end

  def new
    @bridge = current_user.bridges.build
  end

  def edit
  end

  def create
    @bridge = current_user.bridges.build(bridge_params)
    if @bridge.save
      redirect_to @bridge, notice: 'Bridge was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @bridge.update(bridge_params)
      redirect_to @bridge, notice: 'Bridge was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @bridge.destroy
    redirect_to bridges_url, notice: 'Bridge was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bridge
      @bridge = Bridge.find(params[:id])
    end

    def correct_user
      @bridge = current_user.bridges.find_by(id: params[:id])
      redirect_to bridges_path, notice: "Not authorized to edit this bridge" if @bridge.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bridge_params
      params.require(:bridge).permit(:image, :BridgeNo, :Location, :InspectedBy, :InspectDate, :ChiViaNo, :DotCrossNo, :Built, :Type, :Length, :LastInspectDate, :LastRepairs, :NoTypeSpan, :RepairPriority, :GenCond, :Walkway, :ComWalkway, :Handrail, :ComHandrail, :Track, :ComTrack, :Ballast, :ComBallast, :Deck, :ComDeck, :FloorSystem, :ComFloorSystem, :ThruGirder, :ComThruGirder, :Xgirder, :ComXGirder, :Stringer, :ComStringer, :Bearing, :ComBearing, :ColPier, :ComColPier, :Caps, :ComCap, :Post, :ComPost, :Bases, :ComBase, :Abut, :ComAbut, :BackWall, :ComBackWall, :Seat, :ComSeat, :Paint, :ComPaint, :LastPaint, :Light, :ComLight, :MaintLight, :Endpost, :ComEndpost)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridges_helper.rb
module BridgesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bridges/_form.html.erb
<%= form_for(@bridge) do |f| %>
  <% if @bridge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bridge.errors.count, "error") %> prohibited this bridge from being saved:</h2>
      <ul>
      <% @bridge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel panel-default" >
    <div class="form-group">
      <%= f.label :image %><br>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Bridge No:" %><br>
      <%= f.text_field :BridgeNo, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Location %><br>
      <%= f.text_field :Location, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Inspected By" %><br>
      <%= f.text_field :InspectedBy, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Inspection Date:" %><br>
      <%= f.date_select :InspectDate, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Previous Inspection Date:" %><br>
      <%= f.date_select :LastInspectDate, class: "form-control" %>
    </div>    
    <div class="form-group">
      <%= f.label "Chicago Viaduct No:" %><br>
      <%= f.text_field :ChiViaNo, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "DOT Crossing No:" %><br>
      <%= f.text_field :DotCrossNo, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Year Built" %><br>
      <%= f.number_field :Built, min: 1500, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Type %><br>
      <%= f.text_field :Type, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Length(ft):" %><br>
      <%= f.number_field :Length, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "No and Type of Spans:" %><br>
      <%= f.text_field :NoTypeSpan, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Last Repairs:" %><br>
      <%= f.text_field :LastRepairs, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Repair Priority:" %><br>
      <%= f.number_field :RepairPriority, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "General Conditions:" %><br>
      <%= f.text_field :GenCond, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Walkway Rating" %><br>
      <%= f.number_field :Walkway, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Walkway Comments:" %><br>
      <%= f.text_field :ComWalkway, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Handrail Rating:" %><br>
      <%= f.number_field :Handrail, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Handrail Comments:" %><br>
      <%= f.text_field :ComHandrail, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Track Rating:" %><br>
      <%= f.number_field :Track, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Track Comments:" %><br>
      <%= f.text_field :ComTrack, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Ballast Rating:" %><br>
      <%= f.number_field :Ballast, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Ballast Comments:" %><br>
      <%= f.text_field :ComBallast, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Deck Rating:" %><br>
      <%= f.number_field :Deck, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Deck Comments:" %><br>
      <%= f.text_field :ComDeck, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Floor System Rating:" %><br>
      <%= f.number_field :FloorSystem, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Floor System Comments:" %><br>
      <%= f.text_field :ComFloorSystem, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Through Girder Rating:" %><br>
      <%= f.number_field :ThruGirder, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Through Girder Comments:" %><br>
      <%= f.text_field :ComThruGirder, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Cross Girder Rating:" %><br>
      <%= f.number_field :Xgirder, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Cross Girder Comments:" %><br>
      <%= f.text_field :ComXGirder, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Stringer Rating:" %><br>
      <%= f.number_field :Stringer, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Stringer Comments:" %><br>
      <%= f.text_field :ComStringer, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Bearing Rating:" %><br>
      <%= f.number_field :Bearing, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Bearing Comments:" %><br>
      <%= f.text_field :ComBearing, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Column/Pier Rating:" %><br>
      <%= f.number_field :ColPier, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Column/Pier Comments:" %><br>
      <%= f.text_field :ComColPier, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Caps Rating:" %><br>
      <%= f.number_field :Caps, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Caps Comments:" %><br>
      <%= f.text_field :ComCap, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Posts Rating:" %><br>
      <%= f.number_field :Post, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Posts Comments:" %><br>
      <%= f.text_field :ComPost, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Bases Rating:" %><br>
      <%= f.number_field :Bases, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Bases Comments:" %><br>
      <%= f.text_field :ComBase, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Abutments Rating:" %><br>
      <%= f.number_field :Abut, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Abutments Comments" %><br>
      <%= f.text_field :ComAbut, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Backwalls Ratings" %><br>
      <%= f.number_field :BackWall, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Backwalls Comments:" %><br>
      <%= f.text_field :ComBackWall, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Seats Rating:" %><br>
      <%= f.number_field :Seat, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Seats Comments:" %><br>
      <%= f.text_field :ComSeat, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Paint Rating:" %><br>
      <%= f.number_field :Paint, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Paint Comments:" %><br>
      <%= f.text_field :ComPaint, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Last Painted:" %><br>
      <%= f.date_select :LastPaint, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Lighting Rating:" %><br>
      <%= f.number_field :Light, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Lighting Comments:" %><br>
      <%= f.text_field :ComLight, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Lighting Maintained By:" %><br>
      <%= f.text_field :MaintLight, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Endposts Rating:" %><br>
      <%= f.number_field :Endpost, max: 8, min: 1, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "Endposts Comments:" %><br>
      <%= f.text_field :ComEndpost, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit %>
    </div>
</div>
<% end %>

app/views/bridges/edit.html.erb
<h1>Editing Bridge</h1>

<%= render 'form' %>

<%= link_to 'Show', @bridge %> |
<%= link_to 'Back', bridges_path %>

app/views/bridges/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<% if user_signed_in? %>
<div id="bridges" class="transitions-enabled">
  <% @bridges.each do |bridge| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(bridge.image.url(:medium)), bridge %>
      <div class="panel-body">
        <%= bridge.BridgeNo %><br>
        <%= bridge.Location %><br>
        <%= bridge.InspectDate %><br>
        <%= bridge.user.email if bridge.user %><br>
        <%= link_to 'Show', bridge %>
        
        <% if bridge.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_bridge_path(bridge) %>
            <%= link_to 'Destroy', bridge, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/bridges/new.html.erb
<h1>New Bridge</h1>

<%= render 'form' %>

<%= link_to 'Back', bridges_path %>

app/views/bridges/show.html.erb
<%= link_to 'Back', bridges_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @bridge.image.url(:medium) %>
      </div>
      <div class="panel-body">
          <p>
            <strong>Bridge No.:</strong>
            <%= @bridge.BridgeNo %>
          </p>
          <p>
            <strong>Location:</strong>
            <%= @bridge.Location %>
          </p>      
          <p>
            <strong>Inspected By:</strong>
            <%= @bridge.InspectedBy %>
          </p>      
          <p>
            <strong>Inspection Date:</strong>
            <%= @bridge.InspectDate %>
          </p>
          <p>
            <strong>Previous Inspection Date:</strong>
            <%= @bridge.LastInspectDate %>
          </p>       
          <p>
            <strong>Chicago Viaduct No.:</strong>
            <%= @bridge.ChiViaNo %>
          </p>
          <p>
            <strong>DOT Crossing No.:</strong>
            <%= @bridge.DotCrossNo %>
          </p>        
          <p>
            <strong>Built:</strong>
            <%= @bridge.Built %>
          </p>       
          <p>
            <strong>Type:</strong>
            <%= @bridge.Type %>
          </p>       
          <p>
            <strong>Length(ft):</strong>
            <%= @bridge.Length %>
          </p>       
          <p>
            <strong>No. and Type of Spans:</strong>
            <%= @bridge.NoTypeSpan %>
          </p>
          <p>
            <strong>Last Repairs:</strong>
            <%= @bridge.LastRepairs %>
          </p>
          <p>
            <strong>Repair Priority:</strong>
            <%= @bridge.RepairPriority %>
          </p>
          <p>
            <strong>General Conditions</strong>
            <%= @bridge.GenCond %>
          </p>
          <p>
            <strong>Walkway Rating:</strong>
            <%= @bridge.Walkway %>
          </p>
          <p>
            <strong>Walkway Comments</strong>
            <%= @bridge.ComWalkway %>
          </p>
          <p>
          <strong>Handrail Rating:</strong>
          <%= @bridge.Handrail %>
          </p>
          <p>
            <strong>Handrail Comments</strong>
            <%= @bridge.ComHandrail %>
          </p>
          <p>
            <strong>Track Rating:</strong>
            <%= @bridge.Track %>
          </p>
          <p>
            <strong>Track Comments:</strong>
            <%= @bridge.ComTrack %>
          </p>
          <p>
            <strong>Ballast Rating:</strong>
            <%= @bridge.Ballast %>
          </p>
          <p>
            <strong>Ballast Comments:</strong>
            <%= @bridge.ComBallast %>
          </p>
          <p>
            <strong>Deck Rating:</strong>
            <%= @bridge.Deck %>
          </p>
          <p>
            <strong>Deck Comments:</strong>
            <%= @bridge.ComDeck %>
          </p>
          <p>
            <strong>Floor System Rating:</strong>
            <%= @bridge.FloorSystem %>
          </p>
          <p>
            <strong>Floor System Comments:</strong>
            <%= @bridge.ComFloorSystem %>
          </p>
          <p>
            <strong>Through Girder Rating:</strong>
            <%= @bridge.ThruGirder %>
          </p>
          <p>
            <strong>Through Girder Comments:</strong>
            <%= @bridge.ComThruGirder %>
          </p>
          <p>
            <strong>Cross Girder Rating:</strong>
            <%= @bridge.Xgirder %>
          </p>
          <p>
            <strong>Cross Girder Comments:</strong>
            <%= @bridge.ComXGirder %>
          </p>
          <p>
            <strong>Stringer Rating:</strong>
            <%= @bridge.Stringer %>
          </p>
          <p>
            <strong>Stringer Comments:</strong>
            <%= @bridge.ComStringer %>
          </p>
          <p>
            <strong>Bearing Rating:</strong>
            <%= @bridge.Bearing %>
          </p>
          <p>
            <strong>Bearing Comments:</strong>
            <%= @bridge.ComBearing %>
          </p>
          <p>
            <strong>Column/Pier Rating:</strong>
            <%= @bridge.ColPier %>
          </p>
          <p>
            <strong>Column/Pier Comments:</strong>
            <%= @bridge.ComColPier %>
          </p>
          <p>
            <strong>Caps Rating:</strong>
            <%= @bridge.Caps %>
          </p>
          <p>
            <strong>Caps Comments:</strong>
            <%= @bridge.ComCap %>
          </p>
          <p>
            <strong>Posts Rating:</strong>
            <%= @bridge.Post %>
          </p>
          <p>
            <strong>Posts Comments:</strong>
            <%= @bridge.ComPost %>
          </p>
          <p>
            <strong>Bases Rating:</strong>
            <%= @bridge.Bases %>
          </p>
          <p>
            <strong>Bases Comments:</strong>
            <%= @bridge.ComBase %>
          </p>
          <p>
            <strong>Abutments Rating:</strong>
            <%= @bridge.Abut %>
          </p>
          <p>
            <strong>Abutments Comments:</strong>
            <%= @bridge.ComAbut %>
          </p>
          <p>
            <strong>Backwalls Rating:</strong>
            <%= @bridge.BackWall %>
          </p>
          <p>
            <strong>Backwalls Comments:</strong>
            <%= @bridge.ComBackWall %>
          </p>
          <p>
            <strong>Seats Rating:</strong>
            <%= @bridge.Seat %>
          </p>
          <p>
            <strong>Seats Comments:</strong>
            <%= @bridge.ComSeat %>
          </p>
          <p>
            <strong>Paint Rating:</strong>
            <%= @bridge.Paint %>
          </p>
          <p>
            <strong>Paint Comments:</strong>
            <%= @bridge.ComPaint %>
          </p>
          <p>
            <strong>Date of Last Painting:</strong>
            <%= @bridge.LastPaint %>
          </p>
          <p>
            <strong>Lighting Rating:</strong>
            <%= @bridge.Light %>
          </p>
          <p>
            <strong>Lighting Comments:</strong>
            <%= @bridge.ComLight %>
          </p>
          <p>
            <strong>Lights Maintained By:</strong>
            <%= @bridge.MaintLight %>
          </p>
          <p>
            <strong>Endposts Rating:</strong>
            <%= @bridge.Endpost %>
          </p>
          <p>
            <strong>Endposts Comments:</strong>
            <%= @bridge.ComEndpost %>
          </p>
        
        </table>
      </div>
    
<div class="panel panel-footer">
  <% if @bridge.user == current_user %>
    <%= link_to 'Edit', edit_bridge_path(@bridge) %> |
  <% end %>
  <%= link_to 'Back', bridges_path %>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-satic-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to "Bridge Database", root_path %> </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Bridge Number">
	        </div>
	        <button type="submit" class="btn btn-default">Search</button>
	      </form>
        
        <% if user_signed_in? %>
          <li><%= link_to 'New Bridge', new_bridge_path %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bridgedb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
	<body>

		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name,msg| %>
				<%= content_tag(:div, msg, class: "alert-#{name}") %>
	      
	    <% end %>
			<%= yield %>
		</div>

	</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
			<h1>Bridge Database</h1>
     	<p>
				<%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
			</p>

</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h3>Bridge Database</h3>
		
		<% if user_signed_in? %>
			Do something
		<% else %>
     	<p>
				<%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
			</p>
    <% end %>

</div>